# Copyright CERN and copyright holders of ALICE O2. This software is
# distributed under the terms of the GNU General Public License v3 (GPL
# Version 3), copied verbatim in the file "COPYING".
#
# See http://alice-o2.web.cern.ch/ for full licensing information.
#
# In applying this license CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

set(SOURCES
  src/AliRunLoader.cxx
src/AliTRDdEdxParams.cxx
src/AliESDEvent.cxx
src/AliTrackReference.cxx
src/AliKFParticle.cxx
src/AliKalmanTrack.cxx
src/AliVVertex.cxx
src/AliDigitizationInput.cxx
src/AliRawData.cxx
src/AliKFParticleBase.cxx
src/AliEMCALPIDResponse.cxx
src/AliVEvent.cxx
src/AliBaseLoader.cxx
src/AliESDPmdTrack.cxx
src/AliQADataMaker.cxx
src/AliCollisionGeometry.cxx
src/AliDigit.cxx
src/AliLoader.cxx
src/AliHMPIDPid.cxx
src/AliTimeStamp.cxx
src/AliTRDPIDResponse.cxx
src/AliQAChecker.cxx
src/AliDetectorPID.cxx
src/AliMCParticle.cxx
src/AliPIDResponse.cxx
src/AliESDMuonGlobalTrack.cxx
src/AliCluster3D.cxx
src/AliTRDPIDReference.cxx
src/AliRawReaderFile.cxx
src/AliLumiTools.cxx
src/AliTriggerScalersRecord.cxx
src/AliCheb3D.cxx
src/AliESDZDC.cxx
src/AliStack.cxx
src/AliESDcascade.cxx
src/AliTransportMonitor.cxx
src/AliESDv0.cxx
src/AliVertex.cxx
src/AliESDMuonPad.cxx
src/AliHMPIDDigit.cxx
src/AliRunTag.cxx
src/AliEventplane.cxx
src/AliCentrality.cxx
src/AliESDCaloCluster.cxx
src/AliESDACORDE.cxx
src/AliLHCReader.cxx
src/AliESDVertex.cxx
src/AliCDBHandler.cxx
src/AliESDkink.cxx
src/AliQAv1.cxx
src/AliTRDPIDParams.cxx
src/AliVTOFMatch.cxx
src/AliFileTag.cxx
src/AliRawVEvent.cxx
src/AliVParticle.cxx
src/AliRawReader.cxx
src/AliVVZEROfriend.cxx
src/AliTOFPIDResponse.cxx
src/AliQADataMakerSim.cxx
src/AliESDVZEROfriend.cxx
src/AliMagWrapCheb.cxx
src/AliLumiRef.cxx
src/AliDebugVolume.cxx
src/AliESDTOFHit.cxx
src/AliVTPCseed.cxx
src/AliESDCaloTrigger.cxx
src/AliVertexerTracks.cxx
src/AliCDBId.cxx
src/AliTriggerScalersESD.cxx
src/AliMergeCombi.cxx
src/AliVCaloTrigger.cxx
src/AliTRDPIDResponseObject.cxx
src/AliTriggerScalers.cxx
src/AliObjectLoader.cxx
src/AliCluster.cxx
src/AliPlaneEff.cxx
src/AliRawDataErrorLog.cxx
src/AliVTOFHit.cxx
src/AliGeomManager.cxx
src/AliTOFPIDParams.cxx
src/AliVTrack.cxx
src/AliTriggerPFProtection.cxx
src/AliV0HypSel.cxx
src/AliVAD.cxx
src/AliTriggerDescriptor.cxx
src/AliConfig.cxx
src/AliESDTOFMatch.cxx
src/AliQA.cxx
src/AliRunInfo.cxx
src/AliStream.cxx
src/AliITSPIDResponse.cxx
src/AliRawReaderChain.cxx
src/AliHMPIDRawStream.cxx
src/AliRawVEquipment.cxx
src/AliTriggerInput.cxx
src/AliESDtrack.cxx
src/AliTriggerRunScalers.cxx
src/AliTRDTKDInterpolator.cxx
src/AliESDTrdTrigger.cxx
src/AliGenCocktailEventHeader.cxx
src/AliESDFIT.cxx
src/TTreeStream.cxx
src/AliSysInfo.cxx
src/AliESDfriend.cxx
src/AliESDHLTtrack.cxx
src/AliCorrQAChecker.cxx
src/AliFMDMap.cxx
src/AliESDTZERO.cxx
src/AliHeader.cxx
src/AliKFVertex.cxx
src/AliVfriendTrack.cxx
src/AliESDfriendTrack.cxx
src/AliTrackPointArray.cxx
src/AliModule.cxx
src/AliTracker.cxx
src/AliESDCosmicTrack.cxx
src/AliESDRun.cxx
src/AliAlignObjParams.cxx
src/AliVertexGenFile.cxx
src/AliDCSArray.cxx
src/AliRndm.cxx
src/AliESDTZEROfriend.cxx
src/AliESDV0Params.cxx
src/AliESDHeader.cxx
src/AliGenHijingEventHeader.cxx
src/AliMultiplicity.cxx
src/AliGlobalQAChecker.cxx
src/AliTriggerCluster.cxx
src/AliESDTOFCluster.cxx
src/AliHMPIDCluster.cxx
src/AliCDBLocal.cxx
src/AliFstream.cxx
src/AliLego.cxx
src/AliVZDC.cxx
src/AliVTrdTrack.cxx
src/AliITSPidParams.cxx
src/AliVHeader.cxx
src/AliHit.cxx
src/AliGRPObject.cxx
src/AliDetectorRecoParam.cxx
src/AliDCSSensor.cxx
src/AliCDBManager.cxx
src/AliEventTag.cxx
src/AliTrackerBase.cxx
src/AliVMultiplicity.cxx
src/AliSplineFit.cxx
src/AliCDBStorage.cxx
src/AliCTPRawData.cxx
src/AliESDHLTDecision.cxx
src/AliGRPRecoParam.cxx
src/AliCDBGrid.cxx
src/AliVTOFcluster.cxx
src/AliTriggerClass.cxx
src/AliLHCData.cxx
src/AliCDBEntry.cxx
src/AliRawEquipmentHeader.cxx
src/AliTreeLoader.cxx
src/AliTOFHeader.cxx
src/AliRun.cxx
src/AliLHCTag.cxx
src/AliNeutralTrackParam.cxx
src/AliDigitizer.cxx
src/AliMCVertex.cxx
src/AliESDADfriend.cxx
src/AliCDBPath.cxx
src/AliRefArray.cxx
src/AliVertexGenerator.cxx
src/AliQACheckerBase.cxx
src/AliOADBContainer.cxx
src/AliTriggerIR.cxx
src/AliTriggerConfiguration.cxx
src/AliDetectorTag.cxx
src/AliTPCPIDResponse.cxx
src/AliTriggerDetector.cxx
src/AliMultSelectionBase.cxx
src/AliMagFast.cxx
src/AliMagF.cxx
src/AliPID.cxx
src/AliVTrdTracklet.cxx
src/AliBitPacking.cxx
src/AliCDBMetaData.cxx
src/AliTPCdEdxInfo.cxx
src/AliLHCDipValT.cxx
src/AliDetector.cxx
src/AliMCEvent.cxx
src/AliLegoGenerator.cxx
src/AliESDFMD.cxx
src/AliESDTrdTracklet.cxx
src/AliGRPManager.cxx
src/AliESD.cxx
src/AliMC.cxx
src/AliCheb3DCalc.cxx
src/AliESDCaloCells.cxx
src/AliSimulation.cxx
src/AliPIDValues.cxx
src/AliHMPIDPIDResponse.cxx
src/AliTriggerScalersRecordESD.cxx
src/AliTOFTriggerMask.cxx
src/AliVCaloCells.cxx
src/AliESDCalofriend.cxx
src/AliRawEventHeaderBase.cxx
src/AliCodeTimer.cxx
src/AliESDMuonCluster.cxx
src/AliGenerator.cxx
src/AliQAManager.cxx
src/AliEventInfo.cxx
src/AliCentralTrigger.cxx
src/AliVCluster.cxx
src/AliRawReaderRoot.cxx
src/AliESDVZERO.cxx
src/AliCDBRunRange.cxx
src/AliFileUtilities.cxx
src/AliStrLine.cxx
src/AliTriggerBCMask.cxx
src/AliDataLoader.cxx
src/AliExternalTrackParam.cxx
src/AliDAQ.cxx
src/AliGenEventHeader.cxx
src/AliHMPIDPIDParams.cxx
src/AliGlobalQADataMaker.cxx
src/AliRecoParam.cxx
src/AliCorrQADataMakerRec.cxx
src/AliHMPIDParam.cxx
src/AliVMisc.cxx
src/AliQADataMakerRec.cxx
src/AliExpression.cxx
src/AliLog.cxx
src/AliRawReaderDate.cxx
src/AliVVZERO.cxx
src/AliHMPIDRecon.cxx
src/AliTriggerInteraction.cxx
src/AliAlignObj.cxx
src/AliESDMuonTrack.cxx
src/AliESDAD.cxx
src/AliDetectorEventHeader.cxx
src/AliESDTrdTrack.cxx
src/AliCDBDump.cxx
src/AliTRDNDFast.cxx
src/AliPDG.cxx
src/AliFMDFloatMap.cxx
src/AliVfriendEvent.cxx
   )

set(HEADERS
  src/AliFMDFloatMap.h
src/AliVHeader.h
src/AliCorrQADataMakerRec.h
src/AliMagWrapCheb.h
src/AliBaseLoader.h
src/AliCDBEntry.h
src/AliSimulation.h
src/AliESDACORDE.h
src/AliObjectLoader.h
src/AliMultSelectionBase.h
src/AliRecoParam.h
src/AliVZDC.h
src/AliTriggerDetector.h
src/AliTRDPIDReference.h
src/AliESDv0.h
src/AliHMPIDDigit.h
src/AliMCParticle.h
src/AliFastContainerAccess.h
src/AliDetectorTag.h
src/AliMC.h
src/AliESDEvent.h
src/AliCDBId.h
src/AliMagF.h
src/AliSplineFit.h
src/AliModule.h
src/AliVMisc.h
src/AliTriggerIR.h
src/AliESDTZEROfriend.h
src/AliITSPidParams.h
src/AliTRDPIDResponse.h
src/AliDCSSensor.h
src/AliMergeCombi.h
src/AliHMPIDRawStream.h
src/AliVVertex.h
src/AliVCluster.h
src/AliVTrack.h
src/AliGRPRecoParam.h
src/AliLumiTools.h
src/AliRawReaderFile.h
src/AliHit.h
src/AliRawDataErrorLog.h
src/AliCheb3DCalc.h
src/AliTriggerConfiguration.h
src/AliRawReaderDate.h
src/AliFileTag.h
src/AliTRDPIDParams.h
src/AliTriggerPFProtection.h
src/AliVTOFHit.h
src/AliStrLine.h
src/AliKFParticle.h
src/AliDigitizer.h
src/AliCheb3D.h
src/AliLog.h
src/AliTrackerBase.h
src/AliVVZERO.h
src/event.h
src/AliLHCReader.h
src/AliESDAD.h
src/AliCDBManager.h
src/AliTOFPIDResponse.h
src/AliGeomManager.h
src/AliDigitizationInput.h
src/AliTRDPIDResponseObject.h
src/AliBitPacking.h
src/AliRawDataHeaderSim.h
src/AliMCVertex.h
src/AliQADataMakerSim.h
src/AliVTOFMatch.h
src/AliTracker.h
src/TTreeStream.h
src/AliTRDTKDInterpolator.h
src/AliVTrdTrack.h
src/AliOADBContainer.h
src/AliESDCaloCells.h
src/AliCentrality.h
src/AliLHCData.h
src/AliGlobalQADataMaker.h
src/AliTriggerDescriptor.h
src/AliHMPIDParam.h
src/AliGRPManager.h
src/AliDetectorRecoParam.h
src/AliNeutralTrackParam.h
src/AliFileUtilities.h
src/AliLego.h
src/AliTriggerScalersESD.h
src/AliLoader.h
src/AliMCEvent.h
src/AliPID.h
src/AliTrackPointArray.h
src/AliLegoGenerator.h
src/AliRun.h
src/AliCodeTimer.h
src/AliQAv1.h
src/AliAlignObjParams.h
src/AliRawDataHeaderV3.h
src/AliGenEventHeader.h
src/AliTrackReference.h
src/AliQAChecker.h
src/AliGlobalQAChecker.h
src/AliVertexGenFile.h
src/AliVfriendEvent.h
src/AliDataLoader.h
src/AliESDFIT.h
src/AliESDTOFMatch.h
src/AliESDTrdTrack.h
src/AliRefArray.h
src/AliRawReaderChain.h
src/AliTPCdEdxInfo.h
src/AliESDkink.h
src/AliTriggerInput.h
src/AliESDCosmicTrack.h
src/AliKalmanTrack.h
src/AliRawData.h
src/AliCTPRawData.h
src/AliKFParticleBase.h
src/AliITSPIDResponse.h
src/AliTriggerBCMask.h
src/AliTOFHeader.h
src/AliPIDValues.h
src/AliTimeStamp.h
src/AliV0HypSel.h
src/AliHMPIDCluster.h
src/AliLHCDipValT.h
src/AliESDADfriend.h
src/AliTriggerScalersRecord.h
src/AliMultiplicity.h
src/AliTreeLoader.h
src/AliVEvent.h
src/AliCollisionGeometry.h
src/AliEventTag.h
src/AliDetectorEventHeader.h
src/AliTriggerCluster.h
src/AliDAQ.h
src/AliExpression.h
src/AliRawEventHeaderBase.h
src/AliGenerator.h
src/AliPDG.h
src/AliCDBGrid.h
src/AliVTPCseed.h
src/AliTriggerInteraction.h
src/AliRndm.h
src/AliRawReader.h
src/AliQA.h
src/AliLHCTag.h
src/AliESD.h
src/AliCDBRunRange.h
src/AliGenHijingEventHeader.h
src/AliESDTZERO.h
src/AliRawVEquipment.h
src/AliTriggerScalersRecordESD.h
src/AliVTOFcluster.h
src/AliEMCALPIDResponse.h
src/AliESDtrack.h
src/AliStream.h
src/AliDetector.h
src/AliCluster.h
src/AliCDBStorage.h
src/AliCDBLocal.h
src/AliTOFPIDParams.h
src/AliTriggerRunScalers.h
src/AliVertexerTracks.h
src/AliRawReaderRoot.h
src/AliLumiRef.h
src/AliVCaloTrigger.h
src/AliStack.h
src/AliTriggerScalers.h
src/AliTOFTriggerMask.h
src/AliQAManager.h
src/AliDebugVolume.h
src/AliFstream.h
src/AliVParticle.h
src/AliESDVZERO.h
src/AliESDMuonCluster.h
src/AliEventplane.h
src/AliCDBMetaData.h
src/AliESDCaloTrigger.h
src/AliVertexGenerator.h
src/AliESDHeader.h
src/AliExternalTrackParam.h
src/AliESDfriendTrack.h
src/AliESDFMD.h
src/AliVfriendTrack.h
src/AliCDBHandler.h
src/AliTPCPIDResponse.h
src/AliVertex.h
src/AliMiscConstants.h
src/AliHMPIDPIDResponse.h
src/AliESDV0Params.h
src/AliAlignObj.h
src/AliHMPIDPid.h
src/AliESDfriend.h
src/AliRunLoader.h
src/AliVAD.h
src/AliQADataMakerRec.h
src/AliVCaloCells.h
src/AliQADataMaker.h
src/AliDCSArray.h
src/AliRawVEvent.h
src/AliDigit.h
src/AliVVZEROfriend.h
src/AliESDRun.h
src/AliCDBPath.h
src/AliRawDataHeader.h
src/AliTRDdEdxParams.h
src/AliTriggerClass.h
src/AliTransportMonitor.h
src/AliKFVertex.h
src/AliCentralTrigger.h
src/AliESDVZEROfriend.h
src/AliVMultiplicity.h
src/AliESDVertex.h
src/AliESDMuonPad.h
src/AliFMDMap.h
src/AliESDHLTtrack.h
src/AliPlaneEff.h
src/AliSysInfo.h
src/AliHeader.h
src/AliCDBDump.h
src/AliEventInfo.h
src/AliESDHLTDecision.h
src/AliHMPIDRecon.h
src/AliESDPmdTrack.h
src/AliDetectorPID.h
src/AliESDZDC.h
src/AliCorrQAChecker.h
src/AliHMPIDPIDParams.h
src/AliGenCocktailEventHeader.h
src/AliGRPObject.h
src/AliESDTOFHit.h
src/AliESDTOFCluster.h
src/AliConfig.h
src/AliTRDNDFast.h
src/AliQACheckerBase.h
src/AliESDTrdTrigger.h
src/AliRunInfo.h
src/AliESDCaloCluster.h
src/AliMagFast.h
src/AliESDcascade.h
src/AliCluster3D.h
src/AliESDTrdTracklet.h
src/AliRawEquipmentHeader.h
src/AliESDMuonTrack.h
src/AliESDCalofriend.h
src/AliRunTag.h
src/AliVTrdTracklet.h
src/AliESDMuonGlobalTrack.h
src/AliPIDResponse.h
  )
